import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Cedarville_Cursive } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/navbar";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const cedarville = Cedarville_Cursive({
  variable: "--font-cedarville",
  weight: ["400"],
  subsets: ["latin"]
})

export const lato = Lato({
  variable: "--font-lato",
  weight: ["300", "400", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lato.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <NavBar />


        {children}
      </body>
    </html>
  );
}
