import type { Metadata } from "next";
import "./globals.css";
import { lato } from "@/components/fonts/fonts";
import ConditionalNavBar from "@/components/ui/condiotionalnavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${lato.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ConditionalNavBar />
        {children}
      </body>
    </html>
  );
}
